! *** 3 Feb. 2021. - Wavelength Scale   (Max-Min) to (Min-Max) ***
CHARACTER NAME*7, NAM*6
PARAMETER (NU=422,NUG=NU*5+5)
DIMENSION A(NUG),STR(5)
NAME='MODA4.A'

NAM=NAME
OPEN(10,FILE=NAME)
OPEN(11,ACCESS='DIRECT',FORM='UNFORMATTED',RECL=NUG,FILE='_'//NAME)
DO NBDA=1,999
 J=0
 DO  I =1,NU
 READ(10,*,END=1)STR
   DO JJ=1,5
   J=J+1
   A(J)=STR(JJ)
   END DO
 END DO
 WRITE(11,REC=NBDA)A
END DO
1 NUM=NBDA-1
CLOSE(10)
WRITE(*,*)'*** DIRECT File OK! ***',NUM

A=0.
NAME=NAM//'B'
OPEN(10,FILE=NAME)
DO I=NUM,1,-1
READ(11,REC=I)A
BDA=A(1) ;RNN=A(2) ; SC=A(3) ; EXT=A(4) ; AB=A(5)
WRITE(10,2)BDA,RNN,SC,EXT,AB
2 FORMAT(F9.3,F6.1,3E14.5)
   JJ=5
      DO J=2,NU
        DO II=1,5
		 JJ=JJ+1
		 STR(II)=A(JJ)
        END DO
   WRITE(10,*)STR
 !  WRITE(*,*)I,JJ,STR
   END DO 
END DO
CLOSE(10) ; CLOSE(11)
END
 